### ISSUE TITLE
disconnecting consumerClient and subscription

### ISSUE THREAD

**Issue by meizenga** [nicolgit/azure-firewall-mon#31]
Hi @nicolgit. Thanks for developing this, using it currently to monitor AZFW. What I notice is that after some time (a couple minutes I think) the connection to the Event Hub is lost/disconnected. In the bottom of the page it is showing "disconnecting consumerClient and subscription". Pausing and Resuming will reconnect again and the logs flow , for some time and then will stop again.

Is this how it is supposed to work and if so , can we configure/change this?

Thanks in advance!
Marcel

**Comment by nicolgit** [comment]
uhm, yes, it is something I have to look into. Probably a misconfiguration at event hub level.

**Comment by meizenga** [comment]
There is not so much to configure at the event hub. Tried with different access policies and claims. Tried different retention settings. Also redeployed to another region. Also tried your website. The results remain the same; working for some minutes and then stops.

**Comment by nicolgit** [comment]
@meizenga there was a bug in my code. Now should be ok.

**Comment by meizenga** [comment]
Tested and now works as expected. Thanks!
